In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [2]:
df=pd.read_csv('email.csv')

In [3]:
df.head(5)


Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [4]:
df.shape

(5171, 4)

shape of our data

In [5]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [6]:
#missing data
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [7]:
#download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/aniket/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
def process_text(text):
    #remove punctuations,stopwords,return list of clean text words
    nopunc=[char for char in text if char not in string.punctuation]
    nopunc=''.join(nopunc)
    
    clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    return clean_words

In [9]:
df['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
messages=CountVectorizer(analyzer=process_text).fit_transform(df['text'])
messages

<5171x50381 sparse matrix of type '<class 'numpy.int64'>'
	with 374350 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(messages,df['label_num'],test_size=0.20,random_state=0)

In [13]:
messages.shape

(5171, 50381)

In [14]:
#naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [15]:
print(classifier.predict(X_train))

print(y_train.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [16]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print(classification_report(y_train,pred))
print("confusion matrix\n")
print(confusion_matrix(y_train,pred),"\n")
print("ACCURACY ",accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2940
           1       0.98      0.97      0.98      1196

    accuracy                           0.99      4136
   macro avg       0.99      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136

confusion matrix

[[2918   22]
 [  30 1166]] 

ACCURACY  0.9874274661508704


In [17]:
print(classifier.predict(X_test))

print(y_test.values)

[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


In [18]:
pred=classifier.predict(X_test)
print(classification_report(y_test,pred))
print("confusion matrix\n")
print(confusion_matrix(y_test,pred),"\n")
print("ACCURACY ",accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       732
           1       0.95      0.96      0.96       303

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035

confusion matrix

[[718  14]
 [ 13 290]] 

ACCURACY  0.9739130434782609
